CREATE DATABASE RACEDAY;
USE RACEDAY;

--Race Day database schema
CREATE TABLE USERR (UserID INT IDENTITY PRIMARY KEY, NAMEE VARCHAR(150) NOT NULL, Email VARCHAR(255) NOT NULL, PasswordHash VARCHAR(255) NOT NULL,
ROLEE VARCHAR(50) NOT NULL
);
SELECT*FROM USERR;

--Create table for Event
CREATE TABLE EVENTT (EventID INT IDENTITY PRIMARY KEY, OrganiserID INT NOT NULL, 
NAMEE VARCHAR(200) NOT NULL, EventDate DATE NOT NULL, Locationn VARCHAR(255), Descriptionn TEXT, 
CONSTRAINT fk_event_organiser FOREIGN KEY (OrganiserID) REFERENCES USERR(UserID) ON DELETE CASCADE
);
SELECT*FROM EVENTT;

CREATE TABLE CATEGORY (CategoryID INT IDENTITY PRIMARY KEY, EventID INT NOT NULL, 
NAMEE VARCHAR(150) NOT NULL, DistanceKm FLOAT, Price DECIMAL(10,2) NOT NULL DEFAULT 0.00, 
CONSTRAINT fk_category_event FOREIGN KEY (EventID) REFERENCES EVENTT(EventID) ON DELETE CASCADE
);
SELECT*FROM CATEGORY;

CREATE TABLE ROUTEE (RouteID INT IDENTITY PRIMARY KEY, EventID INT NOT NULL, 
RouteName VARCHAR(150) NOT NULL, DistanceKm FLOAT, ElevationGain FLOAT, MapURL VARCHAR(500), 
CONSTRAINT fk_route_event FOREIGN KEY (EventID) REFERENCES EVENTT(EventID) ON DELETE CASCADE
);
SELECT*FROM ROUTEE;

CREATE TABLE REGISTRATION (RegID INT PRIMARY KEY, ParticipantID INT NOT NULL, 
CategoryID INT NOT NULL, RegDate DATE NOT NULL, Status VARCHAR(50) NOT NULL, 
CONSTRAINT fk_registration_category FOREIGN KEY (CategoryID) REFERENCES CATEGORY (CategoryID)
);
SELECT*FROM REGISTRATION;

CREATE TABLE RESULT(
ResultID INT PRIMARY KEY,
EntryID INT NOT NULL UNIQUE, FinishTime TIME, Position INT, Pace VARCHAR(20),
CONSTRAINT fk_result_registration
FOREIGN KEY (ResultID) REFERENCES REGISTRATION(RegID)
);
SELECT*FROM RESULT;